
name: Ubuntu-22.04

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Install requires packages
        run: |
          printf "\n Preparing....\n\n"
          sudo apt update -y > /dev/null 2>&1
          sudo apt install curl openssl -y > /dev/null 2>&1
          bash ./install.sh
